#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-holytech"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
  { "binding": "KV_BINDING", "id": "06e2ad00b0da48ae8068c691015e9e89"}
]
